### PR TITLE
[DEVOPS-1119] fix for spryker build and deployment

### PR DESCRIPTION
**Pull request by g-foster2020**

### CODE REVIEW

**Review by andytson-inviqa — COMMENTED** [review]
I don't know the reason for assets:dump being needed

**Comment by g-foster2020** [comment]
> I don't know the reason for assets:dump being needed

I believe it is so that, on a local rebuild rather than having to create the database again by scripts being executed, it is simply loaded directly from the database dump.  As this is the place to put it, and it was being used in this way in spryker previous to this update, I thought it best to demonstrate where it would go but comment it out as it's not a required step, as per demodata step.

**Comment by andytson-inviqa** [comment]
ok, might be best that is only added when in local environments then

**Comment by andytson-inviqa** [comment]
sorry accidentally closed

**Pull request merged**
