### PR TITLE
Upgrade Magento to 2.4.1

### PR DESCRIPTION
**Pull request by tkotosz**
Magento 2.4.1 will be available on October 15th, but preview already downloadable. I am just sending this draft PR in now and we can revisit it once the upgrade documentation is published.

see https://devdocs.magento.com/release/

### CODE REVIEW

**Comment by kierenevans** [comment]
Pipeline seems okay, shall we merge it?

**Comment by tkotosz** [comment]
@kierenevans I didn't have time to review the upgrade documentation page yet to see if we need to make any additional changes. So on hold for now.

**Comment by tkotosz** [comment]
hmm 2.4.1 doesn't seem to have any release notes (https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)

**Comment by tkotosz** [comment]
https://devdocs-beta.magento.com/guides/v2.4/release-notes/commerce-2-4-1.html - I don't see additional step so it is good to go. @kierenevans

**Review by kierenevans — APPROVED** [review]

**Pull request merged**
