### PR TITLE
Move phpstan configs to skeleton

### PR DESCRIPTION
**Pull request by hgajjar**
Projects would need to overwrite this files very often, so it belongs to skeleton rather than overlay

### CODE REVIEW

**Comment by kierenevans** [comment]
I agree with the phpstan-baseline.neon move, but not sure about the phpstan.neon move - all projects should have the same set of standards

**Comment by Chemaclass** [comment]
> I agree with the phpstan-baseline.neon move, but not sure about the phpstan.neon move - all projects should have the same set of standards

I am not sure about that, @kierenevans. There might be projects where the `level` might be different, but especially the `ignoreErrors` could be totally different depending on the project, no? For example, I am working on a project where I definitely have errors that I want to ignore on purpose that are 100% for our project level.

**Comment by hgajjar** [comment]
@kierenevans thanks for your review, but I also agree with @Chemaclass. Also, we keep it under skeleton in magento2 harness too - https://github.com/inviqa/harness-base-php/blob/1.3.x/src/magento2/application/skeleton/phpstan.neon
Would you agree with it?

**Comment by kierenevans** [comment]
True, okay :+1:

**Review by kierenevans — APPROVED** [review]

**Pull request merged**
