### PR TITLE
Rewrite local.xml on container startup

### PR DESCRIPTION
**Pull request by kierenevans**
Stops local.xml being compiled into the docker image with secrets only valid for the local environment.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
`@('magento.environment')` as well?

a shame after that it's still one more twig block for admin path, otherwise wouldn't need twig (tho if it wasn't EOL, there'd be a valid reason to do that one as well)

**Comment by kierenevans** [comment]
Ah yes, will do :+1:

Still need twig for memcached/redis-session switching

**Comment by andytson-inviqa** [comment]
still seem to be missing `@('magento.environment')`

**Comment by kierenevans** [comment]
Oops, fixed!

**Review by andytson-inviqa — APPROVED** [review]

**Pull request merged**
