### PR TITLE
Add Composer 2.0 Support

### LINKED ISSUE #492: Add composer 2.0 support
Composer 2 has been releases recently. However, there are some old plugins in composer 1 which does not support composer 2 yet. 

So instead of upgrading the existing composer version in base image, we need to see how we can provide support for composer 2 as an option, so that projects can make use of it if their framework/project supports it.

I have opened this issue agains base harness repo, but it might be that we need to make this change in php base image.

### PR DESCRIPTION
**Pull request by kierenevans**
Fixes #492 

* Use a single Dockerfile.twig for console across frameworks 
* Use composer v2 by default for non-framework projects, akeneo, drupal8, magento1, symfony, wordpress
* Use composer v1 by default for magento2 as the magento-composer-installer plugin has no support yet
* Use composer v1 by default for spryker as it seems to have an issue with propel upon installation, so maybe some classes not loading correctly?

<details>
  <summary>Spryker Issue with v2</summary>

```
build@2a8fb861fdc0:/app$ vendor/bin/install -r docker -s generate
========================================================================================================================
Install docker environment                                                                                              
========================================================================================================================

                                                                                                                        
 Section generate                                                                                                       
                                                                                                                        

Command prepare-propel [vendor/bin/console propel:deploy:prepare] (In progress...)
Store: DE | Environment: production
Clean schema directory
Copy and merge schema files
[2020-12-04T16:33:42.881353+00:00] Zed.ERROR: CLI command "propel:deploy:prepare" exception, message "unlink(/app/src/Orm/Propel/Schema/spy_acl.schema.xmly0ZWTM): No such file or directory" {"exception":"[object] (ErrorException(code: 0): unlink(/app/src/Orm/Propel/Schema/spy_acl.schema.xmly0ZWTM): No such file or directory at /app/vendor/symfony/filesystem/Filesystem.php:698)
[stacktrace]
#0 [internal function]: Spryker\\Shared\\ErrorHandler\\ErrorHandlerEnvironment->Spryker\\Shared\\ErrorHandler\\{closure}(2, 'unlink(/app/src...', '/app/vendor/sym...', 698, Array)
#1 /app/vendor/symfony/filesystem/Filesystem.php(698): unlink('/app/src/Orm/Pr...')
#2 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelSchemaWriter.php(43): Symfony\\Component\\Filesystem\\Filesystem->dumpFile('/app/src/Orm/Pr...', '<?xml version=\"...')
#3 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/Model/PropelSchema.php(55): Spryker\\Zed\\Propel\\Business\\Model\\PropelSchemaWriter->write('spy_acl.schema....', '<?xml version=\"...')
#4 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Business/PropelFacade.php(54): Spryker\\Zed\\Propel\\Business\\Model\\PropelSchema->copy()
#5 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Communication/Console/SchemaCopyConsole.php(44): Spryker\\Zed\\Propel\\Business\\PropelFacade->copySchemaFilesToTargetDirectory()
#6 /app/vendor/symfony/console/Command/Command.php(255): Spryker\\Zed\\Propel\\Communication\\Console\\SchemaCopyConsole->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /app/vendor/spryker/kernel/src/Spryker/Zed/Kernel/Communication/Console/Console.php(234): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /app/vendor/spryker/propel/src/Spryker/Zed/Propel/Communication/Console/DeployPreparePropelConsole.php(48): Spryker\\Zed\\Kernel\\Communication\\Console\\Console->runDependingCommand(Object(Spryker\\Zed\\Propel\\Communication\\Console\\SchemaCopyConsole))
#9 /app/vendor/symfony/console/Command/Command.php(255): Spryker\\Zed\\Propel\\Communication\\Console\\DeployPreparePropelConsole->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /app/vendor/symfony/console/Application.php(1027): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spryker\\Zed\\Propel\\Communication\\Console\\DeployPreparePropelConsole), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /app/vendor/spryker/console/src/Spryker/Zed/Console/Communication/Bootstrap/ConsoleBootstrap.php(110): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(149): Spryker\\Zed\\Console\\Communication\\Bootstrap\\ConsoleBootstrap->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /app/vendor/spryker/console/bin/console(27): Symfony\\Component\\Console\\Application->run()
#15 {main}
"} {"environment":{"application":"ZED","environment":"production","store":"DE","codeBucket":"DE","locale":"en_US"},"server":{"url":"http://:/","is_https":false,"hostname":"","user_agent":null,"user_ip":null,"request_method":"cli","referer":null},"request":{"requestId":"932f0650","type":"CLI","request_params":[]}}
ErrorException - Exception: unlink(/app/src/Orm/Propel/Schema/spy_acl.schema.xmly0ZWTM): No such file or directory 
in /app/vendor/symfony/filesystem/Filesystem.php (698)
```
`/app/src/Orm/Propel/Schema/spy_acl.schema.xml` exists after this fails, but it's like the temporary name did not get recorded as having been renamed?

</details>

### CODE REVIEW

**Comment by hgajjar** [comment]
Regarding spryker propel exception, I tried it on another spryker project without this problem, are you sure it's not some temporary problem? doesn't seem like composer 2 related.

**Comment by kierenevans** [comment]
I've pushed up https://github.com/inviqa/harness-base-php/tree/feature/use-composer2-for-spryker to test :+1:

**Comment by hgajjar** [comment]
> I've pushed up https://github.com/inviqa/harness-base-php/tree/feature/use-composer2-for-spryker to test 👍

```
try {
            if (false === @file_put_contents($tmpFile, $content)) {
                throw new IOException(sprintf('Failed to write file "%s".', $filename), 0, null, $filename);
            }

            @chmod($tmpFile, file_exists($filename) ? fileperms($filename) : 0666 & ~umask());

            $this->rename($tmpFile, $filename, true);
        } finally {
            @unlink($tmpFile);
        }
```
This is the original code from `symfony/filesystem` module which causes the error in Spryker build. For safety reason I think, they are unlinking tmpFile in finally with "@" operator. This means it should not throw any error if that file does not exist, but it still throws the error. Apparently this is because Spryker registers it's own error handler here: https://github.com/spryker/error-handler/blob/master/src/Spryker/Shared/ErrorHandler/ErrorHandlerEnvironment.php#L60-L70
As per php's doc, any custom error handler should check if `error_reporting() === 0` and return silently (https://www.php.net/manual/en/language.operators.errorcontrol.php paragraph-2), but this is not what Spryker's error handler is doing, so if I add this check in it, then it lets the build pass successfully.

However, the question is why it has been working ok so far and causing issue only in this branch 😕

**Comment by kierenevans** [comment]
Turns out the drupal autoloader change I made in #497 does not work with composer 2!

**Review by andytson-inviqa — APPROVED** [review]

**Pull request merged**
