### PR TITLE
Avoid copying node_modules to php-fpm

### PR DESCRIPTION
**Pull request by kierenevans**
Hint from @tkotosz, with aim to speed up the build for the php-fpm image from console image step.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I'm wondering why they need to persist in the console static image in the first place

**Review by tkotosz — APPROVED** [review]

**Comment by kierenevans** [comment]
> I'm wondering why they need to persist in the console static image in the first place

Maybe we don't need to have them as the console image is for init/migrate steps and ad-hoc commands.

We'd need to remove them immediately after the FE build completes to avoid being committed to a layer.

I'll raise a separate PR exploring this :)

**Comment by andytson-inviqa** [comment]
adhoc commands wont share the artifacts from console into the nginx container though

**Comment by andytson-inviqa** [comment]
I suppose because we use static builds for CI, if we wanted to do node tests at runtime then that'd be relevant (though I don't like the idea)

**Comment by kierenevans** [comment]
We have a step to install dev dependencies for composer into the running console container, so we can repeat for npm deps too

**Pull request merged**
