### PR TITLE
Switch back to the default docker stop signal in cli images

### PR DESCRIPTION
**Pull request by andytson-inviqa**
Most cli processes don't trap SIGQUIT, so end up being SIGKILLed after 10 seconds of waiting with no graceful handling

### CODE REVIEW

**Review by hgajjar — APPROVED** [review]
LGTM, but I'm not sure if this could have any other side-effects, would be nice to have second opinion

**Review by kierenevans — APPROVED** [review]
SIGTERM is the default, and SIGQUIT is needed only for fpm in https://github.com/docker-library/php/blob/2e2df0625bdf4e882dfcdb314970424abb24f36f/fpm-Dockerfile-block-2#L43.
If we aren't running fpm, it's good to set back to the default :+1:

**Comment by kierenevans** [comment]
Oh perhaps this should be in the https://github.com/my127/docker-php

**Comment by andytson-inviqa** [comment]
>Oh perhaps this should be in the https://github.com/my127/docker-php

In any case the cron service is using the harness-built php-fpm image as a intermediate image, so is needed anyway. That and any upstream image can be specified in the attributes as well, so I think it best in both places

**Pull request merged**
