### PR TITLE
Remove creationTimestamp from ingress

### PR DESCRIPTION
**Pull request by Chemaclass**
## 🔖 Changes

- Fix indentation for `with .Values.ingress.annotations` and `tls`
- Removed `creationTimestamp: null`

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I don't believe there's any issue here, all changes are where the whitespace is truncated `{{-`

**Comment by andytson-inviqa** [comment]
though creationTimestamp you're right to remove (just as status shouldn't be in it)

**Comment by Chemaclass** [comment]
ah, well, it make sense. I apply those indentation fixes because the IDE (PhpStorm) told me that so it looks nicer. Do you want me to rollback those changes? Or is it fine as it is right now? We could remove the creationTimestamp at least in this PR. What do you say, @andytson-inviqa?

**Comment by andytson-inviqa** [comment]
If you rename the ticket to "Remove creationTimestamp from ingresses", then I'd be happy with the formatting changes still in there, however the same changes we'd also make in the base harness https://github.com/inviqa/harness-base-php/blob/1.4.x/src/_base/helm/app/templates/application/webapp/ingress.yaml

**Comment by andytson-inviqa** [comment]
there's actually a few more places that have creationTimestamp in, so I can create a PR that does all of them

**Comment by Chemaclass** [comment]
Yeah, there are creationTimestamp in Deployment, and StatefulSet, but not more Ingress:
Screenshot 2022-05-13 at 13 44 23
Are we sure we want to remove the creationTimestamp from those other places too?

**Comment by andytson-inviqa** [comment]
I'll merge this PR and do a separate one of the other places

**Review by andytson-inviqa — APPROVED** [review]

**Comment by andytson-inviqa** [comment]
You're right to bring up the question, as the rest are all in `template:` fields, it means that they'll all cause a rollout on release even if there's nothing else to change

**Pull request merged**
