### PR TITLE
Add PVCs to Akeneo to persist necessary files

### PR DESCRIPTION
**Pull request by g-foster2020**

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
A more generic solution I'd already started a few weeks ago #161

**Review by andytson-inviqa — CHANGES_REQUESTED** [review]
I'd like consideration for my approach rather than merging this only for mine to be merged as well

**Comment by g-foster2020** [comment]
@andytson-inviqa  That's great in principle but I understand these are needed ASAP yesterday and there is no-one on project to make any changes as we are under pressure to get all the apps deploying to a . client environment.

**Comment by andytson-inviqa** [comment]
there's a way to do it in the projects themselves tho using the overlay

**Pull request closed without merging**
